[features]
seeds = false
skip-lint = false
[programs.localnet]
music_contracts = "48tMte8iJvvYowxzVZdjYXKN19982b1vjxfs8aWFThJG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jimmylevagueresse/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
